#!/bin/bash

while [[ true ]]; do
	
	letsencrypt certonly \
		--text \
		--agree-tos \
		--rsa-key-size 4096 \
		--verbose \
		--renew-by-default \
		--standalone-supported-challenges http-01 \
		--email youremail@example.com \
		-d example.com \
		-d another.example.com \
		--standalone yes
	
	sleep 30d

done
