#!/bin/bash

# days of renewal
# certificate moves around much? shorten renewal period
RENEWAL_PERIOD=30
FILE=/etc/letsencrypt/live/example.com/privkey.pem

while [[ true ]]; do
	
	if [[ $(find "$FILE" -mtime "+${RENEWAL_PERIOD}" -print) ]]; then
	
		letsencrypt certonly \
			--text \
			--agree-tos \
			--rsa-key-size 4096 \
			--verbose \
			--renew-by-default \
			--standalone-supported-challenges http-01 \
			--email youremail@example.com \
			-d example.com \
			-d another.example.com \
			--standalone
	fi
	
	sleep "${RENEWAL_PERIOD}d"

done
